### ISSUE TITLE
Error in nextTick: "NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by Chocogo** [sl1673495/flip-animation#1]
源码的动画效果报错了

**Comment by seolhw** [comment]
index.html 154行代码改成 transform: "unset"

**Comment by sl1673495** [comment]
fixed: [#37841d](https://github.com/sl1673495/flip-animation/commit/37841d4422966733aac2e6e0f35188a9431f17d4)

windows 系统上会有这个问题，mac 不会~
